### ISSUE TITLE
Add support for smart tabs in the file format specification

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig-vote#1]
Related discussion:  editorconfig/editorconfig#323

Each person can vote for one of the 3 options:

1. We do not need it
2. We need it, by creating a `smart_tabs` property, with two options `true` and `false`
3. We need it, by adding a new value `smarttabs` to the option `indent_style`, and introduce a file format version property to take care of backward compatibility issues.

The voting will be closed before Oct 6th 11:59 UTC-12, 2017, if less than half of the members have voted at that time.

@editorconfig/board-member

**Comment by jednano** [comment]
# 2

**Comment by xuhdev** [comment]
# 2

**Comment by hgraeber** [comment]
2

**Comment by sindresorhus** [comment]
𝟸

**Comment by johan** [comment]
Abstain (2 is under-specified, doesn’t include half of the issues raised in #323, and can do as much damage as good to projects).

**Comment by florianb** [comment]
2

**Comment by Mpdreamz** [comment]
1

**Comment by xuhdev** [comment]
OK, over half of us agree on 2. 2 will be the way to go.
