### ISSUE TITLE
Preliminary: Supporting the ability of setting the file type of a file in EditorConfig

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig-vote#10]
Should we consider supporting the ability of setting the file type of a file in EditorConfig, **even assuming no technical difficulty**?

- Voting yes means that you think this feature potentially fits in the overall theme of EditorConfig, and will allow us to start a series of voting regarding the technical details of the implementation, including a possibility of concluding that this is technically infeasible and we should not support this feature.

- Voting no means that we will drop the consideration of this feature now, perhaps because you do not think this feature fits in the theme of EditorConfig or for some other **non-technical reason**.

**Please vote by commenting below: yes or no only. Voting will be closed at the end of Oct 17.**

Discussion please goes to https://github.com/editorconfig/editorconfig/issues/190

@editorconfig/board-member

**Comment by xuhdev** [comment]
yes

**Comment by jednano** [comment]
Yes. It does fit within the theme of EditorConfig.

**Comment by florianb** [comment]
yes

**Comment by sindresorhus** [comment]
yes

**Comment by xuhdev** [comment]
@editorconfig/board-member

**Comment by Mpdreamz** [comment]
Super conflicted about this one. 

Syntax gets into domain specific territory that might be handled better by editor specific properties.

I do however see value in a possible `file_type|syntax` as hints however that editors are free to ignore/implement. Which to me begs the question whether it needs to be a universal property.

Voting `yes` even though some of the complexities in editorconfig/editorconfig#190 scare me. Don't want to block a possible future minimal implementation either.

**Comment by cxw42** [comment]
Any updates?

**Comment by florianb** [comment]
@Mpdreamz - good point, but this vote will allow us to discuss the implementation.

I wouldn't go for maintenance intensive solution at the end - but i understand there is a demand on being able pinning syntax coloring to files where the file ending might be missing or misleading. How we will implement it will be discussed in the following steps.

So hopefully every @editorconfig/board-member did vote?

**Comment by ffes** [comment]
I had not voted yet...

`yes`

**Comment by xuhdev** [comment]
The conclusion is yes then (after so many days...)
