### ISSUE TITLE
Should the version number of the specification (== the version number of editorconfig-core-test) follow the Semantic Versioning 2.0.0 standard (https://semver.org)?

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig-vote#12]
Should the version number of the specification (== the version number of editorconfig-core-test) follow the Semantic Versioning 2.0.0 standard (https://semver.org)?

**Please vote by commenting below: yes or no only. Voting will be closed at the end of May 31.**

Discussion please goes to https://github.com/editorconfig/editorconfig/issues/395

@editorconfig/board-member

cc @cxw42

**Comment by florianb** [comment]
yes

**Comment by sindresorhus** [comment]
yes

**Comment by ffes** [comment]
Yes

**Comment by jednano** [comment]
yes

**Comment by ppalaga** [comment]
yes

**Comment by Mpdreamz** [comment]
yes

**Comment by xuhdev** [comment]
The conclusion is **yes**
