### ISSUE TITLE
Should we remove the upper limit for section name, key and value length?

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig-vote#13]
Currently section names, key, and values have length limit. Should we remove this limit? 

**Please vote by commenting below: yes or no only. Voting will be closed at the end of Dec 18, 2020.**

Discussion goes to https://github.com/editorconfig/editorconfig/issues/429

@editorconfig/board-member

cc @goodhoko @cxw42

**Comment by Mpdreamz** [comment]
Remove 👍

**Comment by jednano** [comment]
Remove 👍

**Comment by ffes** [comment]
Yes, remove

**Comment by ppalaga** [comment]
yes

**Comment by johan** [comment]
remove 👍

**Comment by florianb** [comment]
:+1:

**Comment by xuhdev** [comment]
The conclusion is yes then
