### ISSUE TITLE
Should new property spelling_language be added to the spec?

### ISSUE THREAD

**Issue by cxw42** [editorconfig/editorconfig-vote#15]
This property would specify the natural language for which spelling should be checked in a file.  Example:
```
[czech.txt]
spelling_language = cs
[usenglish.txt]
spelling_language = en-US
```

Note that this property does not specify the charset.  

Related issues: 
* Proposed spec changes to add this property: https://github.com/editorconfig/specification/pull/41
* Request: https://github.com/editorconfig/editorconfig/issues/315

**Please vote by commenting below: yes or no only. Voting will be closed at the end of 2024-01-31.**

Discussion please goes to https://github.com/editorconfig/editorconfig/issues/315

@editorconfig/board-member

CC @mcepl @treyhunner

**Comment by ffes** [comment]
Yes

**Comment by treyhunner** [comment]
Yes

**Comment by Mpdreamz** [comment]
yes

**Comment by sindresorhus** [comment]
Yes

**Comment by xuhdev** [comment]
yes

**Comment by ffes** [comment]
Since it is 2024-02-01, voting is closed.

There are a total of 9 @editorconfig/board-member at this moment and there were 5 vote for `yes` and 0 for `no`.

This means that this property has been accepted.
