### ISSUE TITLE
Support end_of_line = native

### ISSUE THREAD

**Issue by jednano** [editorconfig/editorconfig-vote#2]
Discussion should be at editorconfig/editorconfig#226 .

👍 or 👎 

Let's decide before Nov 1st GMT -12 23:59

### `native` - ensure OS-native line endings

```ini
[*]
end_of_line = native
```

@editorconfig/board-member

**Comment by jednano** [comment]
👍

**Comment by johan** [comment]
👎 As Sindre and Florian point out, the effect of "end_of_line = native" is
to make newlines going into the project a random mess, dependent on what
people run what operating systems. That is the opposite of what
.editorconfig is for.

**Comment by sindresorhus** [comment]
:-1:

**Comment by hgraeber** [comment]
👎 Somehow we already can do that. end_of_line = native would be the same like not to specifing end_of_line at all. To reset to the default end_of_line = unset can be used, which it is already mentioned on http://editorconfig.org/#file-format-details

**Comment by florianb** [comment]
👎  - I agree with @hgraeber, this can already using `unset` or not specifying `end_of_line` at all.

**Comment by xuhdev** [comment]
👍

**Comment by jednano** [comment]
@Mpdreamz , @treyhunner , @ffes do any of you want to vote on this one?

**Comment by ffes** [comment]
~~👎  See [here](https://github.com/editorconfig/editorconfig/issues/226#issuecomment-338954759) why~~

👍 See [here](https://github.com/editorconfig/editorconfig/issues/226#issuecomment-339606318) why

**Comment by xuhdev** [comment]
Shall we close this? According to the rules we have set, even though not all members have voted, this should be closed now.

**Comment by jednano** [comment]
3 👍 and 4 👎 

No feature will be implemented.
