### ISSUE TITLE
Should we add @ppalaga to the board?

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig-vote#3]
@ppalaga submitted an application. Let's vote! @editorconfig/board-member The deadline would be Dec 4 11:59pm. Please reply below as this is something that can be locked afterwards.

**Comment by xuhdev** [comment]
Related issue editorconfig/editorconfig#382

**Comment by Mpdreamz** [comment]
Not sure what the format is but: yes :)

**Comment by xuhdev** [comment]
@Mpdreamz This is not a format... We also need to vote on all new  members according to the [rules](https://github.com/editorconfig/editorconfig/wiki/Board-Member) :)

**Comment by Mpdreamz** [comment]
I meant I don't know how to cast a vote other than replying to the question in the title: yes we should add @ppalaga :)

**Comment by xuhdev** [comment]
@Mpdreamz  Oh, I edited description. You are good, and sorry for the confusion.

@jedmao Can you reply :)

**Comment by jednano** [comment]
:+1: he looks like a stand-up fellow!

**Comment by florianb** [comment]
👍 😄

**Comment by treyhunner** [comment]
:+1: yes/aye

**Comment by xuhdev** [comment]
👍

**Comment by ffes** [comment]
:+1:

**Comment by xuhdev** [comment]
Cool! @ppalaga is in then!
