### ISSUE TITLE
Display ads on the homepage to generate revenue for this project

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig-vote#4]
Should we display ads from Carbon to generate revenue for this project?

Details at: editorconfig/editorconfig.github.com#109

@editorconfig/board-member Please cast your votes by commenting below!

The votes will be closed on Mar 6, 2019, 11:59pm Hawaii Time.

cc @sayzlim

**Comment by xuhdev** [comment]
Yes

**Comment by jednano** [comment]
Yes.

**Comment by sindresorhus** [comment]
Yes

**Comment by ffes** [comment]
Yes

**Comment by florianb** [comment]
Yes

**Comment by ppalaga** [comment]
Yes

**Comment by xuhdev** [comment]
We already have over half members voted for 'yes.' So we will do it! @jedmao and I will work on the preparation by registering an NPO. cc @sayzlim
