### ISSUE TITLE
Backslash/semicolon/octothorpe escaping (again)

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig-vote#6]
This voting would be similar to #5 but is slightly different. #5 voted that we should not add backslash/semicolon/octothorpe escaping into EditorConfig specification before our specification requires to address this issue. Here are two follow-up questions:

- Should we explicitly declare backslash/semicolon/octothorpe escaping undefined in the EditorConfig specification, or leave them unmentioned?
- Should we remove the existing test case `escaped_octothorpe_in_value`, which tests octothorpe escaping?

**Please vote by commenting below: yes or no only (e.g., yes, yes). Voting will be closed at the end of July 5**.

Discussions please go to editorconfig/editorconfig-core-test#24

@editorconfig/board-member cc @rakus

**Comment by xuhdev** [comment]
yes,yes

**Comment by jednano** [comment]
yes,yes

**Comment by xuhdev** [comment]
Ping everybody again: @editorconfig/board-member

**Comment by johan** [comment]
Not a vote, just pointing out that the first question is ternary, not binary: the set of meaningful votes would be ”yes: state as undefined”, ”yes: leave out”, or ”no: no change”.

**Comment by xuhdev** [comment]
> Not a vote, just pointing out that the first question is ternary, not binary: the set of meaningful votes would be ”yes: state as undefined”, ”yes: leave out”, or ”no: no change”.

@johan  The current status is `leave out` :) (i.e., `no change == leave out`)

**Comment by johan** [comment]
Oh, right; 1b) collapses into 1:no). 😄

**Comment by sindresorhus** [comment]
1. Yes
2. Yes

But we should ensure the issue is not forgotten for the formal grammar.

**Comment by rakus** [comment]
Yes/Yes

**Comment by florianb** [comment]
yes, yes

**Comment by xuhdev** [comment]
So the conclusion is yes, yes

**Comment by xuhdev** [comment]
Test removed in editorconfig/editorconfig-core-test@2b983f50beb8fc3f8a09f12a0c16a2abb770390f

**Comment by xuhdev** [comment]
Clarification added in editorconfig/specification@71e10b39ea094833683417ce32d3fefde309d7ae
