### ISSUE TITLE
Should we continue having specification related issues in this repo or in editorconfig/specification?

### ISSUE THREAD

**Issue by xuhdev** [editorconfig/editorconfig-vote#7]
We now have a repo that includes the specification of EditorConfig. For new issues filed by users with regard to specification, should we continue use editorconfig/editorconfig, or editorconfig/specification ? In other words, should we use editorconfig/specification for specification page building issues only, or also use it for actual specification discussion?

**Please vote by commenting below: `eitorconfig/editorconfig` or `editorconfig/specification` only. Voting will be closed at the end of July 28.**

Discussion please goes to editorconfig/editorconfig#398

@editorconfig/board-member

cc @cxw42

**Comment by xuhdev** [comment]
@editorconfig/board-member

**Comment by jednano** [comment]
It looks like most of the issues on `editorconfig/editorconfig` are related to the specification, so it would be a bit of a maintenance nightmare to move all of that over and then add notes to the issue template to tell people to file somewhere else.

I vote to keep the specification discussions where they have been since the beginning and limit this specification repo to the page building issues.

**Comment by ffes** [comment]
`editorconfig/editorconfig`

When that is the outcome, we should consider disabling issues in the other repo.

**Comment by xuhdev** [comment]
`editorconfig/editorconfig`

**Comment by xuhdev** [comment]
We still need two more votes. anyone? @editorconfig/board-member

**Comment by florianb** [comment]
specification - no need to change stuff. we might add a better explanation in the issue-template to avoid wrong issues.

**Comment by xuhdev** [comment]
> specification - no need to change stuff. we might add a better explanation in the issue-template to avoid wrong issues.

"specification" means change...

**Comment by sindresorhus** [comment]
`editorconfig/editorconfig`

**Comment by cxw42** [comment]
What is the official result?

**Comment by xuhdev** [comment]
@florianb Could you clarify what you really meant?

**Comment by xuhdev** [comment]
@florianb Did you mean `editorconfig/editorconfig`? Your explanation seems to support `editorconfig/editorconfig`, but your answer is "specification".

**Comment by florianb** [comment]
I go for `editorconfig/editorconfig`, too.
---
sorry for the late response.

**Comment by xuhdev** [comment]
@florianb Thanks! The conclusion is then we use `editorconfig/editorconfig`.
