### ISSUE TITLE
Support non-existing directories

### ISSUE THREAD

**Issue by jednano** [editorconfig/editorconfig-vote#8]
## The problem

The EditorConfig website doesn't specifically say anything about ~~phantom~~ **non-existing** directories (i.e., directories that don't exist):

> EditorConfig plugins look for a file named .editorconfig in the directory of the opened file and in every parent directory. A search for .editorconfig files will stop if the root filepath is reached or an EditorConfig file with root=true is found.

This leaves it up to the interpretation of plugin developers, which might have introduced inconsistent implementations now and in the future.

## Proposal

Should we support ~~phantom~~ **non-existing** directories? If so, we'll need to add some more text to the paragraph above for clarification. Something like the following:

> ~~Phantom~~ **non-existing** directories (i.e., directories that don't exist) shall be treated like they do exist.

**Please vote by commenting below: yes or no only. Voting will be closed at the end of [a date around two weeks from today].**

Discussion please goes to https://github.com/editorconfig/editorconfig/issues/403

@editorconfig/board-member

cc: @cxw42

### Related
- https://github.com/editorconfig/editorconfig-vim/issues/126

**Comment by xuhdev** [comment]
Yes, as if they exist and were empty

**Comment by florianb** [comment]
I'd propose virtual directory instead of phantom.

**Comment by jedmao** [comment]
Virtual directory already has a very specific CS definition. We could also say non-existing.

**Comment by jednano** [comment]
It's been 15 days and only 3 board members chimed in. I'm assuming the others are neutral on this one. Looks like it's a go!
