### ISSUE TITLE
Should we support a new language rule?

### ISSUE THREAD

**Issue by jednano** [editorconfig/editorconfig-vote#9]
The community [has requested](https://github.com/editorconfig/editorconfig/issues/190) an additional feature in order to specify a language association to any number of file extensions (or filenames) targeted by a glob in the EditorConfig INI format.

We are voting for or against a new [`language`](https://github.com/editorconfig/editorconfig/issues/190#issuecomment-522166996) rule that would look like this:

```ini
[*.js]
language = javascriptreact
```

Values can match any of the [language identifiers](https://code.visualstudio.com/docs/languages/identifiers) currently supported by vscode (as an example or baseline). We need to provide our own list.

**Please vote by commenting below: yes or no only. Voting will be closed at the end of 08/31/2019.**

Discussion please goes to https://github.com/editorconfig/editorconfig/issues/190

@editorconfig/board-member

@xuhdev @10sr

**Comment by jednano** [comment]
Note that the current EditorConfig INI format already supports this, so it requires no format change, just  editor support.

**Comment by SignpostMarv** [comment]
yes

**Comment by asbjornu** [comment]
yes

**Comment by alerque** [comment]
yes

**Comment by florianb** [comment]
yes

**Comment by TriMoon** [comment]
**yes**, when not related in **anyway** with &micro;Sucks products...

**Comment by xuhdev** [comment]
yes

**Comment by eli-schwartz** [comment]
yes

**Comment by sindresorhus** [comment]
No

I like the idea, but I don't think we should vote based on a long discussion. It's not clear what part of the discussion I'm voting on. There needs to be a clear written proposal, that is discussed, and after a set period it goes up for voting. See https://github.com/apple/swift-evolution and https://github.com/rust-lang/rfcs for inspiration.

**Comment by florianb** [comment]
As far as i understood the vote, its about supporting a language rule in general.
How to support it would be the next step, wouldn't it?

I'd like to see taking inspiration from mature projects like rust.

**Comment by sindresorhus** [comment]
> As far as i understood the vote, its about supporting a language rule in general.

That's not clear from the issue text.

**Comment by Mpdreamz** [comment]
No,

I get what the property would do in spirit but fail to see this being implementable in many editors in a generic way.  This would seem best surfaced by editor specific domain properties which can play to each editors language/ecosystem strengths.

**Comment by jednano** [comment]
In response to the confusion about what, exactly, we're voting on, I'm going to close this vote and re-open a new one after https://github.com/editorconfig/editorconfig/issues/190 has settled for a couple days.
